name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm run test
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - uses: actions/upload-artifact@v2
        with:
          name: action.yml
          path: action.yml

  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [built, committed]
    steps:
      - uses: actions/checkout@v2
      - if: matrix.target == 'built' || github.event_name == 'pull_request'
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - if: matrix.target == 'built' || github.event_name == 'pull_request'
        uses: actions/download-artifact@v2
        with:
          name: action.yml
          path: .

      # Repository project tests

      - name: Repo project - create card
        id: coupc-1
        uses: ./
        with:
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 1
          issue-number: 1

      - name: Repo project - card exists
        uses: ./
        with:
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 1
          issue-number: 1

      - name: Repo project - move card
        uses: ./
        with:
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 2
          issue-number: 1

      - name: Repo project - delete card
        uses: actions/github-script@0.9.0
        with:
          script: |
            github.projects.deleteCard({
              card_id: ${{ steps.coupc-1.outputs.card-id }}
            })

      - name: Repo project - create card (pull request)
        if: github.event_name == 'pull_request'
        id: coupc-2
        uses: ./
        with:
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 1
          issue-number: ${{ github.event.number }}

      - name: Repo project - card exists (pull request)
        if: github.event_name == 'pull_request'
        uses: ./
        with:
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 1
          issue-number: ${{ github.event.number }}

      - name: Repo project - delete card (pull request)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@0.9.0
        with:
          script: |
            github.projects.deleteCard({
              card_id: ${{ steps.coupc-2.outputs.card-id }}
            })

      # Org project tests

      - name: Org project - create card
        id: coupc-3
        uses: ./
        with:
          token: ${{ secrets.TEST_CASE_MACHINE_USER_PAT }}
          project-location: create-or-update-project-card
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 1
          repository: create-or-update-project-card/test-fixture
          issue-number: 1

      - name: Org project - card exists
        uses: ./
        with:
          token: ${{ secrets.TEST_CASE_MACHINE_USER_PAT }}
          project-location: create-or-update-project-card
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 1
          repository: create-or-update-project-card/test-fixture
          issue-number: 1

      - name: Org project - move card
        uses: ./
        with:
          token: ${{ secrets.TEST_CASE_MACHINE_USER_PAT }}
          project-location: create-or-update-project-card
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 2
          repository: create-or-update-project-card/test-fixture
          issue-number: 1

      - name: Org project - delete card
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.TEST_CASE_MACHINE_USER_PAT }}
          script: |
            github.projects.deleteCard({
              card_id: ${{ steps.coupc-3.outputs.card-id }}
            })

      # User project tests

      - name: User project - create card
        id: coupc-4
        uses: ./
        with:
          token: ${{ secrets.TEST_CASE_MACHINE_USER_PAT }}
          project-location: test-case-machine-user
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 1
          repository: test-case-machine-user/create-or-update-project-card-fixture
          issue-number: 1

      - name: User project - card exists
        uses: ./
        with:
          token: ${{ secrets.TEST_CASE_MACHINE_USER_PAT }}
          project-location: test-case-machine-user
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 1
          repository: test-case-machine-user/create-or-update-project-card-fixture
          issue-number: 1

      - name: User project - move card
        uses: ./
        with:
          token: ${{ secrets.TEST_CASE_MACHINE_USER_PAT }}
          project-location: test-case-machine-user
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 2
          repository: test-case-machine-user/create-or-update-project-card-fixture
          issue-number: 1

      - name: User project - delete card
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.TEST_CASE_MACHINE_USER_PAT }}
          script: |
            github.projects.deleteCard({
              card_id: ${{ steps.coupc-4.outputs.card-id }}
            })

  package:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update distribution
          title: Update distribution
          body: |
            - Updates the distribution for changes on `main`

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-distribution
